# Generated by Django 5.1.1 on 2024-10-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_scope_is_main_alter_scope_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='is_delete',
        ),
    ]
