# Generated by Django 5.1.1 on 2024-10-31 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_scope_is_delete'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scope',
            unique_together=set(),
        ),
    ]
